keymap:
  - name: Mouse Shortcuts
    remap:
      # Ctrl + Mouse Forward -> Alt + S
      Alt-BTN_EXTRA: Alt-s
      Alt-p: equal
      Alt-o: minus
      Alt-h: left
      Alt-j: down
      Alt-k: up
      Alt-l: right
      Alt-w: Backspace
      # Ctrl + Mouse Back -> Meta (Super) + M
      Alt-BTN_SIDE: Super-m
